#!/bin/sh
##############################################################################
# Functions
##############################################################################
fullpath () {
    if [ $1 ]; then
        ls -d `pwd`/$1
    else
        ls -d `pwd`/*
    fi
}

# Signal handler
TRAPUSR1() {
    # need to source things in to affect parent ENV
    for f in ~/.bash/sighandle/USR1/*; do
        [ -x $f ] && . $f
    done
    unset f
}
trap TRAPUSR1 USR1

# Send signal to all shells
signalit () {
    PATTERN='[-/]bash$'
    SIGNAL=$1

    ps xwwo pid,command | while read pid command; do
        if echo $command | egrep -- "$PATTERN" >/dev/null; then
            kill -$SIGNAL $pid
        fi
    done
}

##############################################################################
# Environment setup
##############################################################################
case "$TERM" in
    screen)
        export PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
        ;;
esac

export CVS_RSH=/usr/bin/ssh

if [ ! -d $HOME/.bash_history_dir ]; then
    mkdir $HOME/.bash_history_dir
fi
export HISTFILE=$HOME/.bash_history_dir/$HOSTNAME.history

export CLICOLOR=1
export EDITOR=vi
export LESSHISTFILE="-"

if [ -x /usr/bin/most ]; then
    export PAGER=/usr/bin/most
else
    export PAGER=/usr/bin/less
fi

export PATH=$PATH:/usr/local/go/bin:$HOME/lib/google_appengine:$HOME/lib/android-sdk-linux_x86/platform-tools:$HOME/lib/android-sdk-linux_x86/tools
export GOROOT=/usr/lib/go
# Use vi bindings for the shell instead of emacs
set -o vi

##############################################################################
# Aliases
##############################################################################
alias usr1='signalit USR1'
alias fp='fullpath'
alias keyon='ssh-add -t 86400'
alias keyoff='ssh-add -D'
alias keylist='ssh-add -l'
alias keylock='ssh-add -x'
alias keyunlock='ssh-add -X'
#alias up='cvs up -AdPf'
#alias ftp='ncftp'
#alias vi='vim'
#alias ls='ls --color=tty'
alias sha1='/usr/bin/openssl sha1'
alias rmd160='/usr/bin/openssl rmd160'
alias blender='LIBGL_ALWAYS_SOFTWARE=1 blender'
alias tmux='tmux -2'
alias java='java -Djava.security.manager'
